on:
  issue_comment:
     types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - run: |
          echo PR number is $NUMBER
        env:
          NUMBER: ${{ github.event.issue.pull_request.number }}
      - run: echo ${{ github.event.comment.body }}
      - name: Checkout PR
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: |
          echo "This is some text to be added to the file." > new_file.txt
      - name: Commit changes
        run: |
          git config --global user.name 'Schema generator'
          git config --global user.email 'chyzhykvv@gmail.com'
          git add .
          git commit -m "Automated report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
