on:
  issue_comment:
     types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          echo "This is some text to be added to the file." > new_file.txt
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - run: |
          echo PR number is $NUMBER
        env:
          NUMBER: ${{ github.event.issue.pull_request.number }}
      - name: Checkout PR
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Add changes
        run: git add .
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Push changes
        run: git commit -m"Schema generated"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
